### ISSUE TITLE
Faster seeking bar?

### ISSUE THREAD

**Issue by rayman3003** [bytespiller/sidplaywx#2]
Thank u for this great sid player.

Is it possible to make the seeking bar go faster?

**Comment by bytespiller** [comment]
I think some change (possibly related to emulation quality) in the libsidplayfp made seeking so slow.  All the players and plugins based on older versions of the lib (both libsidplayfp and its ancestor sidplay2) seek very fast.

For example the zxtune uses an older version of libsidplayfp 1.6.2., and the DeaDBeeF SID plugin uses the ancient sidplay2 library... they both have ultra fast seeking.

I'm unable to verify this because in the [old versions](https://sourceforge.net/projects/sidplay-residfp/files/sidplayfp/1.3/) of the sidplay console program the seeking seems broken.

**Comment by rayman3003** [comment]
> I think some change (possibly related to emulation quality) in the libsidplayfp made seeking so slow. All the players and plugins based on older versions of the lib (both libsidplayfp and its ancestor sidplay2) seek very fast.

OK. If it's about the quality, no can do.

Bcuz the quality must not get compromised, at all cost.

But if u found any solution for this in future (without compromising the quality), please inform me here.

Thank u.

**Comment by nickm-8bit** [comment]
This SID player is truly brilliant btw, great quality indeed! At the risk of stating what we all probably know on here anyway, SID tunes are programs that have to be run and then "rendered" to audio, which is CPU intensive to do a good job. "Genuine" seeking isn't possible because the tune doesn't "exist" as such, so better emulation algorithms will take longer.

**Comment by rayman3003** [comment]
> perhaps it could always render the entire "song"

Yeap. This could be a good solution for having a faster seeking bar.

**Comment by ciros88** [comment]
> Trading off CPU cycles for a moment (maybe a Preferences option?), perhaps it could always render the entire "song" anyway in the background (as it does up until the play point), so as you're listening, if you want to skip forwards, it might have already rendered that part of the song.

wow man this is a very cool idea! thank you!
@bytespiller do you think @nickm-8bit idea could be implemented here?
btw, amazing work, thank u

**Comment by bytespiller** [comment]
> @bytespiller do you think @nickm-8bit idea could be implemented here? what im wondering about is for those sids without songlength? "ahead of time render" should be limited to a max length maybe...

I've thought about it and I'd like to do it, but I'll need to do some code refactoring in multiple areas first.

Yes, sids with unknown songlengths would be limited to user-configured fallback duration (an option which already exists).

**Comment by ciros88** [comment]
I was wondering about: how to handle channel muting/unmuting?  It could be a problem?

**Comment by bytespiller** [comment]
Realtime channel muting/unmuting will be unavailable during playback while the Fast seeking option is enabled.
The voice-toggle checkboxes will be grayed-out (with a message or a tooltip indicating the reason). 

In order for user to change the voice-checkboxes while the Fast seeking option is enabled, the playback will have to be in a stopped state.

**Comment by bytespiller** [comment]
Here is the new v0.7.0 beta version with experimental "Fast seeking" option implemented: https://github.com/bytespiller/sidplaywx/releases/tag/v0.7.0-beta

Please read the release notes at the link for details (especially the last point).

**Comment by rayman3003** [comment]
> Here is the new v0.7.0 beta version with experimental "Fast seeking" option implemented

Thank u very much for enabling this feature. 🙏

instant seeking backwards is fast & awesome. 👌

But the instant seeking forwards still far away from good. It is not bad for songs with less than 1 minute length. But for any song more than that length, we must wait so much! (despite it is faster than before).

Is this the fastest seeking forward, that is possible?

**Comment by bytespiller** [comment]
> It is not bad for songs with less than 1 minute length. But for any song more than that length, we must wait so much! (despite it is faster than before).

If you seek forward before that part had a chance to become pre-rendered you will still have to wait until the pre-rendering catches up (speed of pre-rendering is the same as seek forward but it starts automatically in the background as soon as you start playback).

> Is this the fastest seeking forward, that is possible?

- In the best case scenario seeking forward is instant because the song already had a chance to pre-render (either fully or up to the seek point).
- In the medium case scenario seeking forward is faster because a song is already part-way pre-rendered until the target seek point. 
- In the worst case scenario there is no benefit to Fast seeking option being enabled.
  - The worst case scenario is when the song is long and you immediately seek forward upon the playback start.

**Comment by rayman3003** [comment]
> If you seek forward before that part had a chance to become pre-rendered you will still have to wait until the pre-rendering catches up (speed of pre-rendering is the same as seek forward but it starts automatically in the background as soon as you start playback).

Yeap, thats correct. I see that pre-rendering uses about 25% of my CPU (a 4-core CPU).

But as I said before, we can use GPU (by adding Cuda or GPGPU features), to speed-up the pre-rendering process. In so many cases, GPU can perform faster than CPU (specially if someone has a gaming GPU).

Isn't possible for u to do this?

**Comment by bytespiller** [comment]
Any further speed improvements fall into the domain of the [libsidplayfp](https://github.com/libsidplayfp/libsidplayfp) since the library is what is doing the SID emulation.

During seeking and pre-rendering, the library is already going at its maximum speed and there is no way for a client application (such as sidplaywx) to make it go faster neither by using the GPU nor some extra multi-threading tricks since the SID tunes (programs) can only run linearly from their very beginning so there is nothing to parallelize as far as the client application is concerned.

Only when the libsidplayfp library itself introduces its own speed improvements (be it via optimizations, using GPU, quantum magic or whatever) will client applications (such as sidplaywx) be able to offer greater seeking/rendering speed.

**Comment by rayman3003** [comment]
> Only when the libsidplayfp library itself introduces its own speed improvements

OK, thank u. I will ask them about this.

**Comment by ciros88** [comment]
used it: brilliant @nickm-8bit idea and great @bytespiller impl job.
since this ticket has not been closed yet i have proposal for enhancing the fast seeking user experience:

implement a buffer with a reasonable amount of memory (dinamically calculated based on the total amount of ram) for pre-prenders. then, instead of waiting that the user plays the track for starting the pre-render, you can starts to fill this buffer with pre-renders of multiple tracks as soon as they are added to the playlist taking advantage of parallel processes (as a workaround for lacking of libsidplayfb thread safety) then dropping form the buffer first pre-rendered tracks (FIFO) or the ones already listened (both discarding strategies have pros and cons).

if the user doesn't enable the random playback or, in general, plays the tracks with a linear succession (without jump too much backward or forward in the playlist, depends of the above mentioned discarding strategy) , it will never have to wait for long seeking times.

**Comment by bytespiller** [comment]
I agree in general that with slower seeking it is less convenient to explore the SID tunes (there are so many of them to try and discover new favorites!), but I think it would be wasteful for the player to speculatively pre-render other songs.

I plan to add the "Export to WAV" feature in the future, so perhaps users who want to explore e.g., all tunes by some artist can render them concurrently to disk as audio files so this one meaningful feature then covers multiple use cases.
_You can already export SID tunes to WAV using other software (which also uses libsidplayfp if you care about the quality) such as foobar2000 with foo_sid plugin, command-line sidplayfp etc._

I have currently no plans to implement any other workarounds for the seeking speed.

This issue/ticket remains open for now in case somebody has a **bug report** related to the new experimental "Fast seeking" option.

**Comment by rayman3003** [comment]
> but I think it would be wasteful for the player to speculatively pre-render other songs.

It can always be optional, for users.

**Comment by ciros88** [comment]
i got the @bytespiller point, but i need to say that speculative execution is a well-known and common used computer science strategy for increasing a throughput and/or improve the user experience. i mean, we use it everyday, why not also for an audio player? we buy n-core cpus for this, also :)

maybe, what could be done is simply decide to having a double-buffered strategy: pre-render a single track as soon as it is added to the playlist, and then pre-render the second when this one is finished.

apart from this, i think the idea to have a buffer with a finished amount of memory in order to prevent scenarios with endless renders (loops) and also let the user change the buffer size could be still valid.
